#spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://47.96.21.135:3306/tutumall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 10000





logging:
  level:
    com.tutu.tutumall: debug


spring:
  datasource:
    hikari:
      connection-timeout: 300000
      idleTimeout: 6000000

